'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="EfectiOro")>  _
Partial Public Class ContextoDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub Insertdetacaja(instance As detacaja)
    End Sub
  Partial Private Sub Updatedetacaja(instance As detacaja)
    End Sub
  Partial Private Sub Deletedetacaja(instance As detacaja)
    End Sub
  Partial Private Sub InsertIds(instance As Ids)
    End Sub
  Partial Private Sub UpdateIds(instance As Ids)
    End Sub
  Partial Private Sub DeleteIds(instance As Ids)
    End Sub
  Partial Private Sub Insertadelanto(instance As adelanto)
    End Sub
  Partial Private Sub Updateadelanto(instance As adelanto)
    End Sub
  Partial Private Sub Deleteadelanto(instance As adelanto)
    End Sub
  Partial Private Sub Insertcompras_adelanto(instance As compras_adelanto)
    End Sub
  Partial Private Sub Updatecompras_adelanto(instance As compras_adelanto)
    End Sub
  Partial Private Sub Deletecompras_adelanto(instance As compras_adelanto)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.DataBase.My.MySettings.Default.EfectiOroConnectionString2, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property detacaja() As System.Data.Linq.Table(Of detacaja)
		Get
			Return Me.GetTable(Of detacaja)
		End Get
	End Property
	
	Public ReadOnly Property Ids() As System.Data.Linq.Table(Of Ids)
		Get
			Return Me.GetTable(Of Ids)
		End Get
	End Property
	
	Public ReadOnly Property adelantos() As System.Data.Linq.Table(Of adelanto)
		Get
			Return Me.GetTable(Of adelanto)
		End Get
	End Property
	
	Public ReadOnly Property compras_adelantos() As System.Data.Linq.Table(Of compras_adelanto)
		Get
			Return Me.GetTable(Of compras_adelanto)
		End Get
	End Property
	
	Public ReadOnly Property vconsolidadocajafechas() As System.Data.Linq.Table(Of vconsolidadocajafecha)
		Get
			Return Me.GetTable(Of vconsolidadocajafecha)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.detacaja")>  _
Partial Public Class detacaja
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _idcaja As Decimal
	
	Private _idmov As Integer
	
	Private _hora As String
	
	Private _fecha As Date
	
	Private _concepto As String
	
	Private _efectivo As Decimal
	
	Private _referencia As String
	
	Private _cheque As Decimal
	
	Private _transferencia As Decimal
	
	Private _codcaja As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnidcajaChanging(value As Decimal)
    End Sub
    Partial Private Sub OnidcajaChanged()
    End Sub
    Partial Private Sub OnidmovChanging(value As Integer)
    End Sub
    Partial Private Sub OnidmovChanged()
    End Sub
    Partial Private Sub OnhoraChanging(value As String)
    End Sub
    Partial Private Sub OnhoraChanged()
    End Sub
    Partial Private Sub OnfechaChanging(value As Date)
    End Sub
    Partial Private Sub OnfechaChanged()
    End Sub
    Partial Private Sub OnconceptoChanging(value As String)
    End Sub
    Partial Private Sub OnconceptoChanged()
    End Sub
    Partial Private Sub OnefectivoChanging(value As Decimal)
    End Sub
    Partial Private Sub OnefectivoChanged()
    End Sub
    Partial Private Sub OnreferenciaChanging(value As String)
    End Sub
    Partial Private Sub OnreferenciaChanged()
    End Sub
    Partial Private Sub OnchequeChanging(value As Decimal)
    End Sub
    Partial Private Sub OnchequeChanged()
    End Sub
    Partial Private Sub OntransferenciaChanging(value As Decimal)
    End Sub
    Partial Private Sub OntransferenciaChanged()
    End Sub
    Partial Private Sub OncodcajaChanging(value As String)
    End Sub
    Partial Private Sub OncodcajaChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idcaja", DbType:="Decimal(18,0) NOT NULL", IsPrimaryKey:=true)>  _
	Public Property idcaja() As Decimal
		Get
			Return Me._idcaja
		End Get
		Set
			If ((Me._idcaja = value)  _
						= false) Then
				Me.OnidcajaChanging(value)
				Me.SendPropertyChanging
				Me._idcaja = value
				Me.SendPropertyChanged("idcaja")
				Me.OnidcajaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idmov", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property idmov() As Integer
		Get
			Return Me._idmov
		End Get
		Set
			If ((Me._idmov = value)  _
						= false) Then
				Me.OnidmovChanging(value)
				Me.SendPropertyChanging
				Me._idmov = value
				Me.SendPropertyChanged("idmov")
				Me.OnidmovChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_hora", DbType:="VarChar(50) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property hora() As String
		Get
			Return Me._hora
		End Get
		Set
			If (String.Equals(Me._hora, value) = false) Then
				Me.OnhoraChanging(value)
				Me.SendPropertyChanging
				Me._hora = value
				Me.SendPropertyChanged("hora")
				Me.OnhoraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fecha", DbType:="DateTime")>  _
	Public Property fecha() As Date
		Get
			Return Me._fecha
		End Get
		Set
			If ((Me._fecha = value)  _
						= false) Then
				Me.OnfechaChanging(value)
				Me.SendPropertyChanging
				Me._fecha = value
				Me.SendPropertyChanged("fecha")
				Me.OnfechaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_concepto", DbType:="VarChar(250)", CanBeNull:=false)>  _
	Public Property concepto() As String
		Get
			Return Me._concepto
		End Get
		Set
			If (String.Equals(Me._concepto, value) = false) Then
				Me.OnconceptoChanging(value)
				Me.SendPropertyChanging
				Me._concepto = value
				Me.SendPropertyChanged("concepto")
				Me.OnconceptoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_efectivo", DbType:="Decimal(18,2)")>  _
	Public Property efectivo() As Decimal
		Get
			Return Me._efectivo
		End Get
		Set
			If ((Me._efectivo = value)  _
						= false) Then
				Me.OnefectivoChanging(value)
				Me.SendPropertyChanging
				Me._efectivo = value
				Me.SendPropertyChanged("efectivo")
				Me.OnefectivoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_referencia", DbType:="VarChar(250)", CanBeNull:=false)>  _
	Public Property referencia() As String
		Get
			Return Me._referencia
		End Get
		Set
			If (String.Equals(Me._referencia, value) = false) Then
				Me.OnreferenciaChanging(value)
				Me.SendPropertyChanging
				Me._referencia = value
				Me.SendPropertyChanged("referencia")
				Me.OnreferenciaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cheque", DbType:="Decimal(18,2)")>  _
	Public Property cheque() As Decimal
		Get
			Return Me._cheque
		End Get
		Set
			If ((Me._cheque = value)  _
						= false) Then
				Me.OnchequeChanging(value)
				Me.SendPropertyChanging
				Me._cheque = value
				Me.SendPropertyChanged("cheque")
				Me.OnchequeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_transferencia", DbType:="Decimal(18,2)")>  _
	Public Property transferencia() As Decimal
		Get
			Return Me._transferencia
		End Get
		Set
			If ((Me._transferencia = value)  _
						= false) Then
				Me.OntransferenciaChanging(value)
				Me.SendPropertyChanging
				Me._transferencia = value
				Me.SendPropertyChanged("transferencia")
				Me.OntransferenciaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_codcaja", DbType:="VarChar(10)", CanBeNull:=false)>  _
	Public Property codcaja() As String
		Get
			Return Me._codcaja
		End Get
		Set
			If (String.Equals(Me._codcaja, value) = false) Then
				Me.OncodcajaChanging(value)
				Me.SendPropertyChanging
				Me._codcaja = value
				Me.SendPropertyChanged("codcaja")
				Me.OncodcajaChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Ids")>  _
Partial Public Class Ids
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _codcliente As Integer
	
	Private _codagencia As System.Nullable(Of Integer)
	
	Private _numcompra As System.Nullable(Of Integer)
	
	Private _idadelanto As System.Nullable(Of Integer)
	
	Private _idcompras As System.Nullable(Of Integer)
	
	Private _id_adelantos As System.Nullable(Of Integer)
	
	Private _saldo_anterior As System.Nullable(Of Integer)
	
	Private _cierre_compra As System.Nullable(Of Integer)
	
	Private _prestamo_egreso As System.Nullable(Of Integer)
	
	Private _prestamo_ingreso As System.Nullable(Of Integer)
	
	Private _anular_compra As System.Nullable(Of Integer)
	
	Private _anular_adelanto As System.Nullable(Of Integer)
	
	Private _varias_compras As System.Nullable(Of Boolean)
	
	Private _recibe As String
	
	Private _pago_adelanto As System.Nullable(Of Integer)
	
	Private _idreserva As System.Nullable(Of Integer)
	
	Private _backup As System.Nullable(Of Date)
	
	Private _dolares As System.Nullable(Of Integer)
	
	Private _cordobas As System.Nullable(Of Integer)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OncodclienteChanging(value As Integer)
    End Sub
    Partial Private Sub OncodclienteChanged()
    End Sub
    Partial Private Sub OncodagenciaChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OncodagenciaChanged()
    End Sub
    Partial Private Sub OnnumcompraChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnnumcompraChanged()
    End Sub
    Partial Private Sub OnidadelantoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnidadelantoChanged()
    End Sub
    Partial Private Sub OnidcomprasChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnidcomprasChanged()
    End Sub
    Partial Private Sub Onid_adelantosChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Onid_adelantosChanged()
    End Sub
    Partial Private Sub Onsaldo_anteriorChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Onsaldo_anteriorChanged()
    End Sub
    Partial Private Sub Oncierre_compraChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Oncierre_compraChanged()
    End Sub
    Partial Private Sub Onprestamo_egresoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Onprestamo_egresoChanged()
    End Sub
    Partial Private Sub Onprestamo_ingresoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Onprestamo_ingresoChanged()
    End Sub
    Partial Private Sub Onanular_compraChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Onanular_compraChanged()
    End Sub
    Partial Private Sub Onanular_adelantoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Onanular_adelantoChanged()
    End Sub
    Partial Private Sub Onvarias_comprasChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub Onvarias_comprasChanged()
    End Sub
    Partial Private Sub OnrecibeChanging(value As String)
    End Sub
    Partial Private Sub OnrecibeChanged()
    End Sub
    Partial Private Sub Onpago_adelantoChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub Onpago_adelantoChanged()
    End Sub
    Partial Private Sub OnidreservaChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnidreservaChanged()
    End Sub
    Partial Private Sub OnbackupChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnbackupChanged()
    End Sub
    Partial Private Sub OndolaresChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OndolaresChanged()
    End Sub
    Partial Private Sub OncordobasChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OncordobasChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_codcliente", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property codcliente() As Integer
		Get
			Return Me._codcliente
		End Get
		Set
			If ((Me._codcliente = value)  _
						= false) Then
				Me.OncodclienteChanging(value)
				Me.SendPropertyChanging
				Me._codcliente = value
				Me.SendPropertyChanged("codcliente")
				Me.OncodclienteChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_codagencia", DbType:="Int")>  _
	Public Property codagencia() As System.Nullable(Of Integer)
		Get
			Return Me._codagencia
		End Get
		Set
			If (Me._codagencia.Equals(value) = false) Then
				Me.OncodagenciaChanging(value)
				Me.SendPropertyChanging
				Me._codagencia = value
				Me.SendPropertyChanged("codagencia")
				Me.OncodagenciaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_numcompra", DbType:="Int")>  _
	Public Property numcompra() As System.Nullable(Of Integer)
		Get
			Return Me._numcompra
		End Get
		Set
			If (Me._numcompra.Equals(value) = false) Then
				Me.OnnumcompraChanging(value)
				Me.SendPropertyChanging
				Me._numcompra = value
				Me.SendPropertyChanged("numcompra")
				Me.OnnumcompraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idadelanto", DbType:="Int")>  _
	Public Property idadelanto() As System.Nullable(Of Integer)
		Get
			Return Me._idadelanto
		End Get
		Set
			If (Me._idadelanto.Equals(value) = false) Then
				Me.OnidadelantoChanging(value)
				Me.SendPropertyChanging
				Me._idadelanto = value
				Me.SendPropertyChanged("idadelanto")
				Me.OnidadelantoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idcompras", DbType:="Int")>  _
	Public Property idcompras() As System.Nullable(Of Integer)
		Get
			Return Me._idcompras
		End Get
		Set
			If (Me._idcompras.Equals(value) = false) Then
				Me.OnidcomprasChanging(value)
				Me.SendPropertyChanging
				Me._idcompras = value
				Me.SendPropertyChanged("idcompras")
				Me.OnidcomprasChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_id_adelantos", DbType:="Int")>  _
	Public Property id_adelantos() As System.Nullable(Of Integer)
		Get
			Return Me._id_adelantos
		End Get
		Set
			If (Me._id_adelantos.Equals(value) = false) Then
				Me.Onid_adelantosChanging(value)
				Me.SendPropertyChanging
				Me._id_adelantos = value
				Me.SendPropertyChanged("id_adelantos")
				Me.Onid_adelantosChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_saldo_anterior", DbType:="Int")>  _
	Public Property saldo_anterior() As System.Nullable(Of Integer)
		Get
			Return Me._saldo_anterior
		End Get
		Set
			If (Me._saldo_anterior.Equals(value) = false) Then
				Me.Onsaldo_anteriorChanging(value)
				Me.SendPropertyChanging
				Me._saldo_anterior = value
				Me.SendPropertyChanged("saldo_anterior")
				Me.Onsaldo_anteriorChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cierre_compra", DbType:="Int")>  _
	Public Property cierre_compra() As System.Nullable(Of Integer)
		Get
			Return Me._cierre_compra
		End Get
		Set
			If (Me._cierre_compra.Equals(value) = false) Then
				Me.Oncierre_compraChanging(value)
				Me.SendPropertyChanging
				Me._cierre_compra = value
				Me.SendPropertyChanged("cierre_compra")
				Me.Oncierre_compraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_prestamo_egreso", DbType:="Int")>  _
	Public Property prestamo_egreso() As System.Nullable(Of Integer)
		Get
			Return Me._prestamo_egreso
		End Get
		Set
			If (Me._prestamo_egreso.Equals(value) = false) Then
				Me.Onprestamo_egresoChanging(value)
				Me.SendPropertyChanging
				Me._prestamo_egreso = value
				Me.SendPropertyChanged("prestamo_egreso")
				Me.Onprestamo_egresoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_prestamo_ingreso", DbType:="Int")>  _
	Public Property prestamo_ingreso() As System.Nullable(Of Integer)
		Get
			Return Me._prestamo_ingreso
		End Get
		Set
			If (Me._prestamo_ingreso.Equals(value) = false) Then
				Me.Onprestamo_ingresoChanging(value)
				Me.SendPropertyChanging
				Me._prestamo_ingreso = value
				Me.SendPropertyChanged("prestamo_ingreso")
				Me.Onprestamo_ingresoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_anular_compra", DbType:="Int")>  _
	Public Property anular_compra() As System.Nullable(Of Integer)
		Get
			Return Me._anular_compra
		End Get
		Set
			If (Me._anular_compra.Equals(value) = false) Then
				Me.Onanular_compraChanging(value)
				Me.SendPropertyChanging
				Me._anular_compra = value
				Me.SendPropertyChanged("anular_compra")
				Me.Onanular_compraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_anular_adelanto", DbType:="Int")>  _
	Public Property anular_adelanto() As System.Nullable(Of Integer)
		Get
			Return Me._anular_adelanto
		End Get
		Set
			If (Me._anular_adelanto.Equals(value) = false) Then
				Me.Onanular_adelantoChanging(value)
				Me.SendPropertyChanging
				Me._anular_adelanto = value
				Me.SendPropertyChanged("anular_adelanto")
				Me.Onanular_adelantoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_varias_compras", DbType:="Bit")>  _
	Public Property varias_compras() As System.Nullable(Of Boolean)
		Get
			Return Me._varias_compras
		End Get
		Set
			If (Me._varias_compras.Equals(value) = false) Then
				Me.Onvarias_comprasChanging(value)
				Me.SendPropertyChanging
				Me._varias_compras = value
				Me.SendPropertyChanged("varias_compras")
				Me.Onvarias_comprasChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_recibe", DbType:="VarChar(50)")>  _
	Public Property recibe() As String
		Get
			Return Me._recibe
		End Get
		Set
			If (String.Equals(Me._recibe, value) = false) Then
				Me.OnrecibeChanging(value)
				Me.SendPropertyChanging
				Me._recibe = value
				Me.SendPropertyChanged("recibe")
				Me.OnrecibeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_pago_adelanto", DbType:="Int")>  _
	Public Property pago_adelanto() As System.Nullable(Of Integer)
		Get
			Return Me._pago_adelanto
		End Get
		Set
			If (Me._pago_adelanto.Equals(value) = false) Then
				Me.Onpago_adelantoChanging(value)
				Me.SendPropertyChanging
				Me._pago_adelanto = value
				Me.SendPropertyChanged("pago_adelanto")
				Me.Onpago_adelantoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idreserva", DbType:="Int")>  _
	Public Property idreserva() As System.Nullable(Of Integer)
		Get
			Return Me._idreserva
		End Get
		Set
			If (Me._idreserva.Equals(value) = false) Then
				Me.OnidreservaChanging(value)
				Me.SendPropertyChanging
				Me._idreserva = value
				Me.SendPropertyChanged("idreserva")
				Me.OnidreservaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="[backup]", Storage:="_backup", DbType:="Date")>  _
	Public Property backup() As System.Nullable(Of Date)
		Get
			Return Me._backup
		End Get
		Set
			If (Me._backup.Equals(value) = false) Then
				Me.OnbackupChanging(value)
				Me.SendPropertyChanging
				Me._backup = value
				Me.SendPropertyChanged("backup")
				Me.OnbackupChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_dolares", DbType:="Int")>  _
	Public Property dolares() As System.Nullable(Of Integer)
		Get
			Return Me._dolares
		End Get
		Set
			If (Me._dolares.Equals(value) = false) Then
				Me.OndolaresChanging(value)
				Me.SendPropertyChanging
				Me._dolares = value
				Me.SendPropertyChanged("dolares")
				Me.OndolaresChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cordobas", DbType:="Int")>  _
	Public Property cordobas() As System.Nullable(Of Integer)
		Get
			Return Me._cordobas
		End Get
		Set
			If (Me._cordobas.Equals(value) = false) Then
				Me.OncordobasChanging(value)
				Me.SendPropertyChanging
				Me._cordobas = value
				Me.SendPropertyChanged("cordobas")
				Me.OncordobasChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.adelantos")>  _
Partial Public Class adelanto
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _idsalida As String
	
	Private _codcliente As String
	
	Private _numcompra As String
	
	Private _fecha As Date
	
	Private _monto As System.Nullable(Of Decimal)
	
	Private _saldo As Decimal
	
	Private _efectivo As System.Nullable(Of Decimal)
	
	Private _cheque As System.Nullable(Of Decimal)
	
	Private _transferencia As System.Nullable(Of Decimal)
	
	Private _codcaja As String
	
	Private _usuario As String
	
	Private _monto_letras As String
	
	Private _hora As String
	
	Private _codmoneda As System.Nullable(Of Integer)
	
	Private _compras_adelantos As EntitySet(Of compras_adelanto)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnidsalidaChanging(value As String)
    End Sub
    Partial Private Sub OnidsalidaChanged()
    End Sub
    Partial Private Sub OncodclienteChanging(value As String)
    End Sub
    Partial Private Sub OncodclienteChanged()
    End Sub
    Partial Private Sub OnnumcompraChanging(value As String)
    End Sub
    Partial Private Sub OnnumcompraChanged()
    End Sub
    Partial Private Sub OnfechaChanging(value As Date)
    End Sub
    Partial Private Sub OnfechaChanged()
    End Sub
    Partial Private Sub OnmontoChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnmontoChanged()
    End Sub
    Partial Private Sub OnsaldoChanging(value As Decimal)
    End Sub
    Partial Private Sub OnsaldoChanged()
    End Sub
    Partial Private Sub OnefectivoChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnefectivoChanged()
    End Sub
    Partial Private Sub OnchequeChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnchequeChanged()
    End Sub
    Partial Private Sub OntransferenciaChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OntransferenciaChanged()
    End Sub
    Partial Private Sub OncodcajaChanging(value As String)
    End Sub
    Partial Private Sub OncodcajaChanged()
    End Sub
    Partial Private Sub OnusuarioChanging(value As String)
    End Sub
    Partial Private Sub OnusuarioChanged()
    End Sub
    Partial Private Sub Onmonto_letrasChanging(value As String)
    End Sub
    Partial Private Sub Onmonto_letrasChanged()
    End Sub
    Partial Private Sub OnhoraChanging(value As String)
    End Sub
    Partial Private Sub OnhoraChanged()
    End Sub
    Partial Private Sub OncodmonedaChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OncodmonedaChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._compras_adelantos = New EntitySet(Of compras_adelanto)(AddressOf Me.attach_compras_adelantos, AddressOf Me.detach_compras_adelantos)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idsalida", DbType:="VarChar(20) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property idsalida() As String
		Get
			Return Me._idsalida
		End Get
		Set
			If (String.Equals(Me._idsalida, value) = false) Then
				Me.OnidsalidaChanging(value)
				Me.SendPropertyChanging
				Me._idsalida = value
				Me.SendPropertyChanged("idsalida")
				Me.OnidsalidaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_codcliente", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property codcliente() As String
		Get
			Return Me._codcliente
		End Get
		Set
			If (String.Equals(Me._codcliente, value) = false) Then
				Me.OncodclienteChanging(value)
				Me.SendPropertyChanging
				Me._codcliente = value
				Me.SendPropertyChanged("codcliente")
				Me.OncodclienteChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_numcompra", DbType:="VarChar(MAX) NOT NULL", CanBeNull:=false)>  _
	Public Property numcompra() As String
		Get
			Return Me._numcompra
		End Get
		Set
			If (String.Equals(Me._numcompra, value) = false) Then
				Me.OnnumcompraChanging(value)
				Me.SendPropertyChanging
				Me._numcompra = value
				Me.SendPropertyChanged("numcompra")
				Me.OnnumcompraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fecha", DbType:="Date NOT NULL")>  _
	Public Property fecha() As Date
		Get
			Return Me._fecha
		End Get
		Set
			If ((Me._fecha = value)  _
						= false) Then
				Me.OnfechaChanging(value)
				Me.SendPropertyChanging
				Me._fecha = value
				Me.SendPropertyChanged("fecha")
				Me.OnfechaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_monto", DbType:="Decimal(18,2)")>  _
	Public Property monto() As System.Nullable(Of Decimal)
		Get
			Return Me._monto
		End Get
		Set
			If (Me._monto.Equals(value) = false) Then
				Me.OnmontoChanging(value)
				Me.SendPropertyChanging
				Me._monto = value
				Me.SendPropertyChanged("monto")
				Me.OnmontoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_saldo", DbType:="Decimal(18,2) NOT NULL")>  _
	Public Property saldo() As Decimal
		Get
			Return Me._saldo
		End Get
		Set
			If ((Me._saldo = value)  _
						= false) Then
				Me.OnsaldoChanging(value)
				Me.SendPropertyChanging
				Me._saldo = value
				Me.SendPropertyChanged("saldo")
				Me.OnsaldoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_efectivo", DbType:="Decimal(18,2)")>  _
	Public Property efectivo() As System.Nullable(Of Decimal)
		Get
			Return Me._efectivo
		End Get
		Set
			If (Me._efectivo.Equals(value) = false) Then
				Me.OnefectivoChanging(value)
				Me.SendPropertyChanging
				Me._efectivo = value
				Me.SendPropertyChanged("efectivo")
				Me.OnefectivoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cheque", DbType:="Decimal(18,2)")>  _
	Public Property cheque() As System.Nullable(Of Decimal)
		Get
			Return Me._cheque
		End Get
		Set
			If (Me._cheque.Equals(value) = false) Then
				Me.OnchequeChanging(value)
				Me.SendPropertyChanging
				Me._cheque = value
				Me.SendPropertyChanged("cheque")
				Me.OnchequeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_transferencia", DbType:="Decimal(18,2)")>  _
	Public Property transferencia() As System.Nullable(Of Decimal)
		Get
			Return Me._transferencia
		End Get
		Set
			If (Me._transferencia.Equals(value) = false) Then
				Me.OntransferenciaChanging(value)
				Me.SendPropertyChanging
				Me._transferencia = value
				Me.SendPropertyChanged("transferencia")
				Me.OntransferenciaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_codcaja", DbType:="VarChar(10)")>  _
	Public Property codcaja() As String
		Get
			Return Me._codcaja
		End Get
		Set
			If (String.Equals(Me._codcaja, value) = false) Then
				Me.OncodcajaChanging(value)
				Me.SendPropertyChanging
				Me._codcaja = value
				Me.SendPropertyChanged("codcaja")
				Me.OncodcajaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_usuario", DbType:="VarChar(50)")>  _
	Public Property usuario() As String
		Get
			Return Me._usuario
		End Get
		Set
			If (String.Equals(Me._usuario, value) = false) Then
				Me.OnusuarioChanging(value)
				Me.SendPropertyChanging
				Me._usuario = value
				Me.SendPropertyChanged("usuario")
				Me.OnusuarioChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_monto_letras", DbType:="VarChar(MAX)")>  _
	Public Property monto_letras() As String
		Get
			Return Me._monto_letras
		End Get
		Set
			If (String.Equals(Me._monto_letras, value) = false) Then
				Me.Onmonto_letrasChanging(value)
				Me.SendPropertyChanging
				Me._monto_letras = value
				Me.SendPropertyChanged("monto_letras")
				Me.Onmonto_letrasChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_hora", DbType:="VarChar(50)")>  _
	Public Property hora() As String
		Get
			Return Me._hora
		End Get
		Set
			If (String.Equals(Me._hora, value) = false) Then
				Me.OnhoraChanging(value)
				Me.SendPropertyChanging
				Me._hora = value
				Me.SendPropertyChanged("hora")
				Me.OnhoraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_codmoneda", DbType:="Int")>  _
	Public Property codmoneda() As System.Nullable(Of Integer)
		Get
			Return Me._codmoneda
		End Get
		Set
			If (Me._codmoneda.Equals(value) = false) Then
				Me.OncodmonedaChanging(value)
				Me.SendPropertyChanging
				Me._codmoneda = value
				Me.SendPropertyChanged("codmoneda")
				Me.OncodmonedaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="adelanto_compras_adelanto", Storage:="_compras_adelantos", ThisKey:="idsalida", OtherKey:="idadelanto")>  _
	Public Property compras_adelantos() As EntitySet(Of compras_adelanto)
		Get
			Return Me._compras_adelantos
		End Get
		Set
			Me._compras_adelantos.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_compras_adelantos(ByVal entity As compras_adelanto)
		Me.SendPropertyChanging
		entity.adelanto = Me
	End Sub
	
	Private Sub detach_compras_adelantos(ByVal entity As compras_adelanto)
		Me.SendPropertyChanging
		entity.adelanto = Nothing
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.compras_adelantos")>  _
Partial Public Class compras_adelanto
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _idcompras_adelantos As Integer
	
	Private _numcompra As String
	
	Private _idadelanto As String
	
	Private _codcliente As String
	
	Private _sinicial As Decimal
	
	Private _monto As Decimal
	
	Private _sfinal As Decimal
	
	Private _fecha As Date
	
	Private _codcaja As String
	
	Private _usuario As String
	
	Private _hora As System.TimeSpan
	
	Private _codagencia As String
	
	Private _codmoneda As System.Nullable(Of Integer)
	
	Private _adelanto As EntityRef(Of adelanto)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub Onidcompras_adelantosChanging(value As Integer)
    End Sub
    Partial Private Sub Onidcompras_adelantosChanged()
    End Sub
    Partial Private Sub OnnumcompraChanging(value As String)
    End Sub
    Partial Private Sub OnnumcompraChanged()
    End Sub
    Partial Private Sub OnidadelantoChanging(value As String)
    End Sub
    Partial Private Sub OnidadelantoChanged()
    End Sub
    Partial Private Sub OncodclienteChanging(value As String)
    End Sub
    Partial Private Sub OncodclienteChanged()
    End Sub
    Partial Private Sub OnsinicialChanging(value As Decimal)
    End Sub
    Partial Private Sub OnsinicialChanged()
    End Sub
    Partial Private Sub OnmontoChanging(value As Decimal)
    End Sub
    Partial Private Sub OnmontoChanged()
    End Sub
    Partial Private Sub OnsfinalChanging(value As Decimal)
    End Sub
    Partial Private Sub OnsfinalChanged()
    End Sub
    Partial Private Sub OnfechaChanging(value As Date)
    End Sub
    Partial Private Sub OnfechaChanged()
    End Sub
    Partial Private Sub OncodcajaChanging(value As String)
    End Sub
    Partial Private Sub OncodcajaChanged()
    End Sub
    Partial Private Sub OnusuarioChanging(value As String)
    End Sub
    Partial Private Sub OnusuarioChanged()
    End Sub
    Partial Private Sub OnhoraChanging(value As System.TimeSpan)
    End Sub
    Partial Private Sub OnhoraChanged()
    End Sub
    Partial Private Sub OncodagenciaChanging(value As String)
    End Sub
    Partial Private Sub OncodagenciaChanged()
    End Sub
    Partial Private Sub OncodmonedaChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OncodmonedaChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._adelanto = CType(Nothing, EntityRef(Of adelanto))
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idcompras_adelantos", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property idcompras_adelantos() As Integer
		Get
			Return Me._idcompras_adelantos
		End Get
		Set
			If ((Me._idcompras_adelantos = value)  _
						= false) Then
				Me.Onidcompras_adelantosChanging(value)
				Me.SendPropertyChanging
				Me._idcompras_adelantos = value
				Me.SendPropertyChanged("idcompras_adelantos")
				Me.Onidcompras_adelantosChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_numcompra", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property numcompra() As String
		Get
			Return Me._numcompra
		End Get
		Set
			If (String.Equals(Me._numcompra, value) = false) Then
				Me.OnnumcompraChanging(value)
				Me.SendPropertyChanging
				Me._numcompra = value
				Me.SendPropertyChanged("numcompra")
				Me.OnnumcompraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idadelanto", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property idadelanto() As String
		Get
			Return Me._idadelanto
		End Get
		Set
			If (String.Equals(Me._idadelanto, value) = false) Then
				If Me._adelanto.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException()
				End If
				Me.OnidadelantoChanging(value)
				Me.SendPropertyChanging
				Me._idadelanto = value
				Me.SendPropertyChanged("idadelanto")
				Me.OnidadelantoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_codcliente", DbType:="VarChar(20)")>  _
	Public Property codcliente() As String
		Get
			Return Me._codcliente
		End Get
		Set
			If (String.Equals(Me._codcliente, value) = false) Then
				Me.OncodclienteChanging(value)
				Me.SendPropertyChanging
				Me._codcliente = value
				Me.SendPropertyChanged("codcliente")
				Me.OncodclienteChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sinicial", DbType:="Decimal(18,2) NOT NULL")>  _
	Public Property sinicial() As Decimal
		Get
			Return Me._sinicial
		End Get
		Set
			If ((Me._sinicial = value)  _
						= false) Then
				Me.OnsinicialChanging(value)
				Me.SendPropertyChanging
				Me._sinicial = value
				Me.SendPropertyChanged("sinicial")
				Me.OnsinicialChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_monto", DbType:="Decimal(18,3) NOT NULL")>  _
	Public Property monto() As Decimal
		Get
			Return Me._monto
		End Get
		Set
			If ((Me._monto = value)  _
						= false) Then
				Me.OnmontoChanging(value)
				Me.SendPropertyChanging
				Me._monto = value
				Me.SendPropertyChanged("monto")
				Me.OnmontoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_sfinal", DbType:="Decimal(18,2) NOT NULL")>  _
	Public Property sfinal() As Decimal
		Get
			Return Me._sfinal
		End Get
		Set
			If ((Me._sfinal = value)  _
						= false) Then
				Me.OnsfinalChanging(value)
				Me.SendPropertyChanging
				Me._sfinal = value
				Me.SendPropertyChanged("sfinal")
				Me.OnsfinalChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fecha", DbType:="Date NOT NULL")>  _
	Public Property fecha() As Date
		Get
			Return Me._fecha
		End Get
		Set
			If ((Me._fecha = value)  _
						= false) Then
				Me.OnfechaChanging(value)
				Me.SendPropertyChanging
				Me._fecha = value
				Me.SendPropertyChanged("fecha")
				Me.OnfechaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_codcaja", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
	Public Property codcaja() As String
		Get
			Return Me._codcaja
		End Get
		Set
			If (String.Equals(Me._codcaja, value) = false) Then
				Me.OncodcajaChanging(value)
				Me.SendPropertyChanging
				Me._codcaja = value
				Me.SendPropertyChanged("codcaja")
				Me.OncodcajaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_usuario", DbType:="VarChar(20) NOT NULL", CanBeNull:=false)>  _
	Public Property usuario() As String
		Get
			Return Me._usuario
		End Get
		Set
			If (String.Equals(Me._usuario, value) = false) Then
				Me.OnusuarioChanging(value)
				Me.SendPropertyChanging
				Me._usuario = value
				Me.SendPropertyChanged("usuario")
				Me.OnusuarioChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_hora", DbType:="Time NOT NULL")>  _
	Public Property hora() As System.TimeSpan
		Get
			Return Me._hora
		End Get
		Set
			If ((Me._hora = value)  _
						= false) Then
				Me.OnhoraChanging(value)
				Me.SendPropertyChanging
				Me._hora = value
				Me.SendPropertyChanged("hora")
				Me.OnhoraChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_codagencia", DbType:="VarChar(10)")>  _
	Public Property codagencia() As String
		Get
			Return Me._codagencia
		End Get
		Set
			If (String.Equals(Me._codagencia, value) = false) Then
				Me.OncodagenciaChanging(value)
				Me.SendPropertyChanging
				Me._codagencia = value
				Me.SendPropertyChanged("codagencia")
				Me.OncodagenciaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_codmoneda", DbType:="Int")>  _
	Public Property codmoneda() As System.Nullable(Of Integer)
		Get
			Return Me._codmoneda
		End Get
		Set
			If (Me._codmoneda.Equals(value) = false) Then
				Me.OncodmonedaChanging(value)
				Me.SendPropertyChanging
				Me._codmoneda = value
				Me.SendPropertyChanged("codmoneda")
				Me.OncodmonedaChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.AssociationAttribute(Name:="adelanto_compras_adelanto", Storage:="_adelanto", ThisKey:="idadelanto", OtherKey:="idsalida", IsForeignKey:=true)>  _
	Public Property adelanto() As adelanto
		Get
			Return Me._adelanto.Entity
		End Get
		Set
			Dim previousValue As adelanto = Me._adelanto.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._adelanto.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._adelanto.Entity = Nothing
					previousValue.compras_adelantos.Remove(Me)
				End If
				Me._adelanto.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.compras_adelantos.Add(Me)
					Me._idadelanto = value.idsalida
				Else
					Me._idadelanto = CType(Nothing, String)
				End If
				Me.SendPropertyChanged("adelanto")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.vconsolidadocajafecha")>  _
Partial Public Class vconsolidadocajafecha
	
	Private _idcaja As Decimal
	
	Private _codrubro As System.Nullable(Of Integer)
	
	Private _descrubro As String
	
	Private _idmov As Integer
	
	Private _descripcion As String
	
	Private _fecha As System.Nullable(Of Date)
	
	Private _efectivo As System.Nullable(Of Decimal)
	
	Private _transferencias As System.Nullable(Of Decimal)
	
	Private _cheque As System.Nullable(Of Decimal)
	
	Private _codcaja As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idcaja", DbType:="Decimal(18,0) NOT NULL")>  _
	Public Property idcaja() As Decimal
		Get
			Return Me._idcaja
		End Get
		Set
			If ((Me._idcaja = value)  _
						= false) Then
				Me._idcaja = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_codrubro", DbType:="Int")>  _
	Public Property codrubro() As System.Nullable(Of Integer)
		Get
			Return Me._codrubro
		End Get
		Set
			If (Me._codrubro.Equals(value) = false) Then
				Me._codrubro = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_descrubro", DbType:="VarChar(250) NOT NULL", CanBeNull:=false)>  _
	Public Property descrubro() As String
		Get
			Return Me._descrubro
		End Get
		Set
			If (String.Equals(Me._descrubro, value) = false) Then
				Me._descrubro = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_idmov", DbType:="Int NOT NULL")>  _
	Public Property idmov() As Integer
		Get
			Return Me._idmov
		End Get
		Set
			If ((Me._idmov = value)  _
						= false) Then
				Me._idmov = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_descripcion", DbType:="VarChar(250) NOT NULL", CanBeNull:=false)>  _
	Public Property descripcion() As String
		Get
			Return Me._descripcion
		End Get
		Set
			If (String.Equals(Me._descripcion, value) = false) Then
				Me._descripcion = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fecha", DbType:="DateTime")>  _
	Public Property fecha() As System.Nullable(Of Date)
		Get
			Return Me._fecha
		End Get
		Set
			If (Me._fecha.Equals(value) = false) Then
				Me._fecha = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_efectivo", DbType:="Decimal(38,2)")>  _
	Public Property efectivo() As System.Nullable(Of Decimal)
		Get
			Return Me._efectivo
		End Get
		Set
			If (Me._efectivo.Equals(value) = false) Then
				Me._efectivo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_transferencias", DbType:="Decimal(38,2)")>  _
	Public Property transferencias() As System.Nullable(Of Decimal)
		Get
			Return Me._transferencias
		End Get
		Set
			If (Me._transferencias.Equals(value) = false) Then
				Me._transferencias = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_cheque", DbType:="Decimal(38,2)")>  _
	Public Property cheque() As System.Nullable(Of Decimal)
		Get
			Return Me._cheque
		End Get
		Set
			If (Me._cheque.Equals(value) = false) Then
				Me._cheque = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_codcaja", DbType:="VarChar(10)")>  _
	Public Property codcaja() As String
		Get
			Return Me._codcaja
		End Get
		Set
			If (String.Equals(Me._codcaja, value) = false) Then
				Me._codcaja = value
			End If
		End Set
	End Property
End Class
